### ISSUE TITLE
Missing training details

### ISSUE THREAD

**Issue by beginnerkeeplearning** [bcmi/Object-Placement-Assessment-Dataset-OPA#1]
Good work and nice dataset!
I am trying to use this dataset and train a resnet18 as in the paper. But I cannot reproduce the result. Could anyone provide details about how the resnet18 is trained? For example, what is augmentation and optimization strategy? How is the data sampled? 
Hope someone can provide details for this.

**Comment by ustcnewly** [comment]
Thanks for your attention. We will release our code and model after the paper is accepted.

**Comment by ustcnewly** [comment]
We have released the code and model of SimOPA.
