### ISSUE TITLE
Google Drive link only includes composites

### ISSUE THREAD

**Issue by benjaminwfriedman** [bcmi/Object-Placement-Assessment-Dataset-OPA#6]
Hello, unless I have done something wrong it seems like the google drive link provided in this repo only includes composite images rather than the described structure: 

├── background:
     ├── category:
              ├── imgID.jpg
              ├── ……
     ├── ……
├── foreground:
     ├── category:
              ├── imgID.jpg
              ├── mask_imgID.jpg
              ├── ……
     ├── ……
├── composite:
     ├── train_set:
              ├── fgimgID_bgimgID_x_y_w_h_scale_label.jpg
              ├── mask_fgimgID_bgimgID_x_y_w_h_scale_label.jpg
              ├── ……
     └── test_set:
├── train_set.csv
└── test_set.csv

Your GracoNet implementation seems to rely on this too.

**Comment by WhynotHAHA** [comment]
I downloaded the dataset from the google drive link and unzipped it to get the following file directory. Could you please provide more details on the download process or try downloading again?
<img width="762" alt="截屏2024-01-31 12 11 59" src="https://github.com/bcmi/Object-Placement-Assessment-Dataset-OPA/assets/92723497/36f86f56-dad8-46cc-aece-5a1e8f226f5d">

**Comment by benjaminwfriedman** [comment]
Hey sorry took me a second to get back to you. When I unzipped it on my local it worked great. The original issue occured trying to extract it in an azure ml workspace using the linux unrar command. Just documenting incase it is helpful in the future, extracting on my local windows machine worked great. Thanks

**Comment by wtliao** [comment]
> I downloaded the dataset from the google drive link and unzipped it to get the following file directory. Could you please provide more details on the download process or try downloading again? <img alt="截屏2024-01-31 12 11 59" width="762" src="https://private-user-images.githubusercontent.com/92723497/301036966-36f86f56-dad8-46cc-aece-5a1e8f226f5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMjE1NjUsIm5iZiI6MTczMzIyMTI2NSwicGF0aCI6Ii85MjcyMzQ5Ny8zMDEwMzY5NjYtMzZmODZmNTYtZGFkOC00NmNjLWFlY2UtNWExZThmMjI2ZjVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDEwMjEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxYzgxMjc5NWMwODRmZjAwMzA0MWZjMTQyM2ZjOTQ3NjliN2E5M2MwODVlOGVmYTkxYTllNTcwOTYwODE5YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CwZ4Lsk2lKpibFpcPN2CBErgxNo4EWJvR841631ArpI">

Hi, I am trying to unzip the '.rar' file in my local mac using '7z', but got error for each file. Could you let me know what tool you used to unzip it? Thanks!
<img width="881" alt="Screenshot 2024-12-03 at 11 24 05" src="https://github.com/user-attachments/assets/5c78ea58-bcd8-413c-9cae-729565ed4c39">
